<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-GOITT5R" failures="1" tests="6" name="sila_test_cases.Check_kyc" time="310.246" errors="0" timestamp="2020-11-20T17:23:24 IST" skipped="0">
  <testcase classname="sila_test_cases.Check_kyc" name="Test_01_Check_kyc_with_not_requested_kyc_user_handle" time="4.425"/>
  <system-out/>
  <testcase classname="sila_test_cases.Check_kyc" name="Test_02_Check_kyc_verification_pending" time="1.406"/>
  <system-out/>
  <testcase classname="sila_test_cases.Check_kyc" name="Test_03_Check_kyc_verification_successfully_passed" time="300.717">
    <failure message="expected [SUCCESS] but found [FAILURE]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [SUCCESS] but found [FAILURE]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at sila_test_cases.Check_kyc.Test_03_Check_kyc_verification_successfully_passed(Check_kyc.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Test_03_Check_kyc_verification_successfully_passed -->
  <system-out/>
  <testcase classname="sila_test_cases.Check_kyc" name="Test_04_Check_kyc_with_unregistered_user_handle" time="1.495"/>
  <system-out/>
  <testcase classname="sila_test_cases.Check_kyc" name="Test_05_Check_kyc_with_empty_user_handle" time="0.508"/>
  <system-out/>
  <testcase classname="sila_test_cases.Check_kyc" name="Test_06_Check_kyc_with_invalid_signature" time="1.695"/>
  <system-out/>
</testsuite> <!-- sila_test_cases.Check_kyc -->
